### ISSUE TITLE
Create list of open source code that we are using

### ISSUE THREAD

**Issue by dazuck** [3box/ops#247]
to add detail - something we likely have to do, should be quick but needs to be right + comprehensive. I'll start a template once ready.

**Comment by michaelsena** [comment]
Is this for legal reasons? I see you added it to my workload this sprint... @dazuck

**Comment by kuhnchris** [comment]
... sorry to butt it: Couldn't you simply do that by merging the package.json files? Basically all of those should be OSS. Or do you mean "using" as in backend-frontend side like nginx/apache/lighttpd, etc.?

**Comment by dazuck** [comment]
@michaelsena yes, legal. I'm still gathering timeline and exact need but it should be light if we have to do it this sprint, led by lawyers. Literally just a list. No action yet and hoping to push back, just wanted you to have early visibility that it may be something we need to do in the next week. 

@kuhnchris I'm not sure yet, still finding out what the need is :) But thanks for the suggestion.

**Comment by dazuck** [comment]
@oed @zachferland @oznekenzo Can you please take a look at this and prioritize it. https://www.notion.so/threebox/Open-Source-Disclosure-f24b4ab358584f0584e0847aad759869

it would be a huge help if we can have by end of week. Will bring up in standup tomorrow.

**Comment by dazuck** [comment]
@oed I've invited you (and others) to Fosso. it's flagging ~10 possible issues, but I think most won't be problems. I started to scan but you're going to be 10x faster on making sense of the code side. Can you take a look when up (presuming you can log in) and if not we can do quickly together tomorrow? This is pretty high priority to get done ASAP for legal.

**Comment by oed** [comment]
@dazuck I've looked though and resolved most of them now. Mostly nothing to be concerned with. muport-core-js still has two issues, but it doesn't matter since we are not using this lib anymore. 

The main problem is https://github.com/ConsenSys/abi-decoder which is GPL. Which means that the dapp would need to be GPL as well. This wouldn't be much of a problem though. 
Longer term we don't need this dep as we move over to alethio. I can also ask the author to change the license if needed 🙂
